### ISSUE TITLE
The ReScience C template is non-free

### ISSUE THREAD

**Issue by broukema** [ReScience/template#13]
The ReScicence C template for submittable articles is non-free.
Apart from the fonts directories, there is no indication of the licence
of the files. Thus, under the Berne Convention, the files are non-free.
While a court would probably accept that authors modifying the template
and using it to submit articles for publication in ReScience C are complying
with the intentions of the authors, that's much weaker than a free licence.

A suggested commit to fix this is here: https://github.com/ReScience/template/pull/12

**Comment by rougier** [comment]
Thanks for pointing this. Let's move the discussion to your proposed PR.
