### ISSUE TITLE
space before asterisk in affiliation causes problems

### ISSUE THREAD

**Issue by sje30** [ReScience/template#17]
hi,
If we (accidently) put a space before asterisk in affiliation list, then we get the following error:

```
make
./yaml-to-latex.py -i metadata.yaml -o metadata.tex
Traceback (most recent call last):
  File "./yaml-to-latex.py", line 93, in <module>
    content = generate_latex_metadata(filename_in, article)
  File "./yaml-to-latex.py", line 10, in generate_latex_metadata
    "% DO NOT EDIT - automatically generated from {filename}\n\n"
AttributeError: 'str' object has no attribute 'name'
```

see: https://github.com/sje30/test2/commit/0878bcac746e4d012e012e5dfb3dc49a9f1e5158

fixed in the obvious way (deleting the space), but it took me about 15 minutes to find it...

**Comment by rougier** [comment]
Ouch, sorry for that. Can you make a PR to fix the problem (latest version is here: https://github.com/ReScience/articles)

**Comment by sje30** [comment]
I'm afraid I don't have a fix (to make it insensitive to white space), but rather deleted the space that crept into our version of the yaml.
