### ISSUE TITLE
Unable to include author suffix

### ISSUE THREAD

**Issue by schackartk** [ReScience/template#29]
Currently, the way `metadata.yaml` is parsed does not allow for author suffixes. For example, when I publish I prefer to include my suffix, *e.g.* "Kenneth E. Schackart III". But with the current parser, "III" is taken to be my last name since it is just splitting the name on whitespace and taking the last piece to be the last name. This means that the copyright statement shows "K.E.S. III" and the footnote just shows "III 2023".

I see two obvious ways of addressing this:

1. Do some more complex parsing of the name to determine if the last portion is a suffix.
2. Add an (optional) suffix field in the `metadata.yaml` and handle that during parsing.

I will be opening a pull request taking the second approach. I think this is likely the more robust approach.

**Comment by schackartk** [comment]
The pull request (#30) works for making `metadata.tex` and the `article.pdf` while including author name suffixes. I am not sure where else `metadata.yaml` is used on ReScience's side.

**Comment by schackartk** [comment]
I have provided a second pull request (#31 ) which is simpler and has fewer changes to the code. Importantly, it does not require modification of `metadata.yaml`.

**Comment by schackartk** [comment]
During the development of these pull requests, I realized that the code allows for names formatted as "Last, First M.I.". This scheme works with a suffix since it is splitting on the comma to get first and last names instead of splitting on white space.
One just needs to enter their name as "Last Suffix, First M.I." (*e.g.* "Schackart III, Kenneth E.").
If the editors wish to not accept either pull request, a comment could be added to `metadata.yaml` stating that if authors wish to include a suffix, format the name as "Last Suffix, First M.I."

**Comment by rougier** [comment]
I read all your contributions in reverse order :) I think we can go with the simpler comment in the metadata.yaml that would not break thing too much. We're transitioning to a new system (JOSS) and hopefully things will be more robust.

**Comment by schackartk** [comment]
Thanks for taking a look! And I look forward to seeing the new system.

I'll submit a pull request with only an added comment to metadata.yaml and I will close my previous pull requests.

Until the transition is complete, anyone who wishes to can use [my fork](https://github.com/schackartk/rescience_template/tree/add_suffix_simpler) (from #31) that enables names to be formatted as "First M.I. Last Suffix" in the pdf and does not change metadata.yaml.
